version: '3.8'

services:
  server:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    restart: always

  client:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
